#!/bin/bash

set -e

if [[ ! -f /.dockerenv ]]; then
    echo "This script was written for repo2docker and is supposed to run inside a docker container."
    echo "Exiting because this script can delete data if run outside of a docker container."
    exit 1
fi

TMP_DIR=/tmp/pyfstat
mkdir -p $TMP_DIR
cp -r examples/*/*.py .binder $TMP_DIR
find . -delete

# Generate notebooks and remove other files from examples folder
NOTEBOOKS_SCRIPTS_DIR=.generated-notebooks
mkdir -p $NOTEBOOKS_SCRIPTS_DIR
cp -r $TMP_DIR/* $NOTEBOOKS_SCRIPTS_DIR

## Here, exclude whatever must be excluded
find $NOTEBOOKS_SCRIPTS_DIR -name '*.py' ! -name '*run_all*' ! -name '*transient*' ! -name '*glitch*' -exec sphx_glr_python_to_jupyter.py '{}' +

mkdir -p notebooks/PyFstat-examples
ln -s ../$NOTEBOOKS_SCRIPTS_DIR notebooks/auto_examples
