#!/bin/bash

set -e

if [[ ! -f /.dockerenv ]]; then
    echo "This script was written for repo2docker and is supposed to run inside a docker container."
    echo "Exiting because this script can delete data if run outside of a docker container."
    exit 1
fi

# Get the example scripts from the latest tagged release 
TMP_DIR=/tmp/pyfstat
PIP_DIR=/tmp/pip_download
mkdir -p ${TMP_DIR}
mkdir -p ${PIP_DIR}

pip download --no-deps --no-binary pyfstat pyfstat --dest ${PIP_DIR}
tar -xvzf ${PIP_DIR}/*.tar.gz -C ${PIP_DIR} --wildcards *examples 
cp -r ${PIP_DIR}/*/examples*/*.py .binder $TMP_DIR

find . -delete

# Generate notebooks from the python scripts
NOTEBOOKS_SCRIPTS_DIR=.generated-notebooks
mkdir -p $NOTEBOOKS_SCRIPTS_DIR

cp -r $TMP_DIR/* $NOTEBOOKS_SCRIPTS_DIR

find $NOTEBOOKS_SCRIPTS_DIR -name '*.py' ! -name '*run_all*' ! -name '*transient*' ! -name '*glitch*' -exec sphx_glr_python_to_jupyter.py '{}' +

# This symlink is required
mkdir notebooks
ln -s ../$NOTEBOOKS_SCRIPTS_DIR notebooks/auto_examples
